######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 29 16:37:12 2018
# not depend on QT
# only C++
######################################################################

TEMPLATE = lib
TARGET = common
DEPENDPATH += .
INCLUDEPATH += .
DESTDIR = $${PWD}/../../../bin

HEADERS += \
    $$PWD/vec.h \
    $$PWD/shape.h \
    $$PWD/color.h \
    $$PWD/trans.h

SOURCES += \
    $$PWD/trans.cpp

